### ISSUE TITLE
Doesn't quite work

### ISSUE THREAD

**Issue by malte-v** [stoand/kakoune-idris#6]
Thanks for making this plugin!

Whenever I'm trying to run an IDE action, the relevant part gets selected after a short delay, but the action is not performed. The following error message shows up in the debug buffer:

```
shell stderr: <<<
/nix/store/g3q2j8l1jjqpcx84yc0skwcl2a38imr8-kak-idris/share/kak/autoload/plugins/idris/ide-mode-actions.js:48
    return exprs.concat().reverse().find(e => e[0] == ':return').find(e => e[0] == ':ok')[1];
                                                                ^

TypeError: Cannot read property 'find' of undefined
    at lastRetVal (/nix/store/g3q2j8l1jjqpcx84yc0skwcl2a38imr8-kak-idris/share/kak/autoload/plugins/idris/ide-mode-actions.js:48:65)
    at /nix/store/g3q2j8l1jjqpcx84yc0skwcl2a38imr8-kak-idris/share/kak/autoload/plugins/idris/ide-mode-actions.js:69:29
    at idrisExec (/nix/store/g3q2j8l1jjqpcx84yc0skwcl2a38imr8-kak-idris/share/kak/autoload/plugins/idris/ide-mode-actions.js:42:20)
    at exports.caseSplit (/nix/store/g3q2j8l1jjqpcx84yc0skwcl2a38imr8-kak-idris/share/kak/autoload/plugins/idris/ide-mode-actions.js:68:12)
    at Object.<anonymous> (/nix/store/g3q2j8l1jjqpcx84yc0skwcl2a38imr8-kak-idris/share/kak/autoload/plugins/idris/ide-mode-run.js:22:17)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
>>>
```

**Comment by stoand** [comment]
Hi,

I updated my Idris2 to the latest version but wasn't able to reproduce your error.

I made changes so that all stdio output is written to `/tmp/__kak_idris2_exprs` .

Could you pull my changes and send me your `/tmp/__kak_idris2_exprs`?

You could also try running `node ide-mode-test.js` to see if your end-to-end tests work.

**Comment by malte-v** [comment]
I found the problem: My .ipkg file was empty. Maybe you should replace the `touch myproject.ipkg` in the README with an example .ipkg? It's kind of misleading.
